--
-- Table structure for table `form_labcorp_order`
--

CREATE TABLE IF NOT EXISTS `form_labcorp_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` datetime NOT NULL,
  `pid` bigint(20) NOT NULL,
  `user` varchar(255) NOT NULL,
  `groupname` varchar(255) NOT NULL,
  `authorized` tinyint(4) DEFAULT NULL,
  `activity` tinyint(4) DEFAULT NULL,
  `status` varchar(16) DEFAULT NULL,
  `priority` varchar(16) DEFAULT NULL,
  `facility_id` int(11) DEFAULT NULL,
  `labcorp_siteid` varchar(25) DEFAULT NULL,
  `pubpid` varchar(25) DEFAULT NULL,
  `pat_first` varchar(255) DEFAULT NULL,
  `pat_middle` varchar(255) DEFAULT NULL,
  `pat_last` varchar(255) DEFAULT NULL,
  `pat_DOB` date DEFAULT NULL,
  `pat_ss` varchar(15) DEFAULT NULL,
  `pat_age` varchar(255) DEFAULT NULL,
  `pat_sex` varchar(255) DEFAULT NULL,
  `pat_race` varchar(255) NOT NULL,
  `pat_ethnicity` varchar(255) NOT NULL,
  `pat_height` varchar(5) DEFAULT NULL,
  `pat_weight` varchar(5) DEFAULT NULL,
  `pat_email` varchar(255) DEFAULT NULL,
  `pat_mobile` varchar(255) DEFAULT NULL,
  `pat_phone` varchar(255) DEFAULT NULL,
  `pat_street` varchar(255) DEFAULT NULL,
  `pat_city` varchar(255) DEFAULT NULL,
  `pat_state` varchar(255) DEFAULT NULL,
  `pat_zip` varchar(255) DEFAULT NULL,
  `ins_first` varchar(255) DEFAULT NULL,
  `ins_middle` varchar(255) DEFAULT NULL,
  `ins_last` varchar(255) DEFAULT NULL,
  `ins_DOB` date DEFAULT NULL,
  `ins_sex` varchar(2) DEFAULT NULL,
  `ins_ss` varchar(15) DEFAULT NULL,
  `ins_relation` varchar(255) DEFAULT NULL,
  `ins_primary` varchar(255) DEFAULT NULL,
  `ins_primary_id` varchar(255) DEFAULT NULL,
  `ins_primary_plan` varchar(255) DEFAULT NULL,
  `ins_primary_policy` varchar(255) DEFAULT NULL,
  `ins_primary_group` varchar(255) DEFAULT NULL,
  `ins_secondary` varchar(255) DEFAULT NULL,
  `ins_secondary_id` varchar(255) DEFAULT NULL,
  `ins_secondary_plan` varchar(255) DEFAULT NULL,
  `ins_secondary_policy` varchar(255) DEFAULT NULL,
  `ins_secondary_group` varchar(255) DEFAULT NULL,
  `ins_tertiary` varchar(255) DEFAULT NULL,
  `ins_tertiary_id` varchar(255) DEFAULT NULL,
  `ins_tertiary_plan` varchar(255) DEFAULT NULL,
  `ins_tertiary_policy` varchar(255) DEFAULT NULL,
  `ins_tertiary_group` varchar(255) DEFAULT NULL,
  `guarantor_first` varchar(255) DEFAULT NULL,
  `guarantor_middle` varchar(255) DEFAULT NULL,
  `guarantor_last` varchar(255) DEFAULT NULL,
  `guarantor_relation` varchar(255) DEFAULT NULL,
  `guarantor_street` varchar(255) DEFAULT NULL,
  `guarantor_city` varchar(255) DEFAULT NULL,
  `guarantor_state` varchar(255) DEFAULT NULL,
  `guarantor_zip` varchar(255) DEFAULT NULL,
  `guarantor_ss` varchar(255) DEFAULT NULL,
  `guarantor_phone` varchar(255) DEFAULT NULL,
  `dx0_code` varchar(255) DEFAULT NULL,
  `dx0_text` varchar(255) DEFAULT NULL,
  `dx1_code` varchar(255) DEFAULT NULL,
  `dx1_text` varchar(255) DEFAULT NULL,
  `dx2_code` varchar(255) DEFAULT NULL,
  `dx2_text` varchar(255) DEFAULT NULL,
  `dx3_code` varchar(255) DEFAULT NULL,
  `dx3_text` varchar(255) DEFAULT NULL,
  `dx4_code` varchar(255) DEFAULT NULL,
  `dx4_text` varchar(255) DEFAULT NULL,
  `dx5_code` varchar(255) DEFAULT NULL,
  `dx5_text` varchar(255) DEFAULT NULL,
  `dx6_code` varchar(255) DEFAULT NULL,
  `dx6_text` varchar(255) DEFAULT NULL,
  `dx7_code` varchar(255) DEFAULT NULL,
  `dx7_text` varchar(255) DEFAULT NULL,
  `dx8_code` varchar(255) DEFAULT NULL,
  `dx8_text` varchar(255) DEFAULT NULL,
  `dx9_code` varchar(255) DEFAULT NULL,
  `dx9_text` varchar(255) DEFAULT NULL,
  `copy_pat` tinyint(1) NOT NULL DEFAULT '0',
  `copy_acct` varchar(25) DEFAULT NULL,
  `copy_acctname` varchar(255) DEFAULT NULL,
  `copy_fax` varchar(25) DEFAULT NULL,
  `copy_faxname` varchar(255) DEFAULT NULL,
  `order_number` varchar(225) NOT NULL,
  `order_datetime` datetime DEFAULT NULL,
  `order_done` tinyint(4) DEFAULT NULL,
  `order_zseg` varchar(255) DEFAULT NULL,
  `order_type` varchar(255) DEFAULT NULL,
  `order_psc` tinyint(4) DEFAULT NULL,
  `order_fasting` varchar(4) DEFAULT NULL,
  `order_duration` varchar(255) DEFAULT NULL,
  `order_volume` varchar(20) DEFAULT NULL,
  `order_req_id` varchar(255) DEFAULT NULL,
  `order_abn_id` varchar(255) DEFAULT NULL,
  `order_abn_signed` char(1) NOT NULL,
  `order_notes` text,
  `work_flag` char(1) NOT NULL,
  `work_insurance` varchar(25) NOT NULL,
  `work_date` date NOT NULL,
  `work_employer` varchar(25) NOT NULL,
  `work_case` varchar(25) NOT NULL,
  `request_provider` varchar(255) DEFAULT NULL,
  `request_billing` varchar(5) DEFAULT NULL,
  `request_account` varchar(25) DEFAULT NULL,
  `request_facility` varchar(255) DEFAULT NULL,
  `request_handling` varchar(255) DEFAULT NULL,
  `request_datetime` datetime DEFAULT NULL,
  `request_processed` datetime DEFAULT NULL,
  `request_notes` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_idx` (`order_number`),
  KEY `pid_idx` (`pid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `form_labcorp_order_aoe`
--

CREATE TABLE IF NOT EXISTS `form_labcorp_order_aoe` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `parent_id` bigint(20) NOT NULL,
  `date` datetime NOT NULL,
  `pid` bigint(20) NOT NULL,
  `user` varchar(255) NOT NULL,
  `groupname` varchar(255) DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT NULL,
  `activity` tinyint(4) DEFAULT NULL,
  `status` varchar(16) DEFAULT 'i',
  `priority` varchar(16) DEFAULT 'n',
  `zseg` varchar(10) DEFAULT NULL,
  `aoe0_code` varchar(10) DEFAULT NULL,
  `aoe0_label` varchar(90) DEFAULT NULL,
  `aoe0_list` varchar(30) DEFAULT NULL,
  `aoe0_text` varchar(255) DEFAULT NULL,
  `aoe1_code` varchar(10) DEFAULT NULL,
  `aoe1_label` varchar(90) DEFAULT NULL,
  `aoe1_list` varchar(30) DEFAULT NULL,
  `aoe1_text` varchar(255) DEFAULT NULL,
  `aoe2_code` varchar(10) DEFAULT NULL,
  `aoe2_label` varchar(90) DEFAULT NULL,
  `aoe2_list` varchar(30) DEFAULT NULL,
  `aoe2_text` varchar(255) DEFAULT NULL,
  `aoe3_code` varchar(10) DEFAULT NULL,
  `aoe3_label` varchar(90) DEFAULT NULL,
  `aoe3_list` varchar(30) DEFAULT NULL,
  `aoe3_text` varchar(255) DEFAULT NULL,
  `aoe4_code` varchar(10) DEFAULT NULL,
  `aoe4_label` varchar(90) DEFAULT NULL,
  `aoe4_list` varchar(30) DEFAULT NULL,
  `aoe4_text` varchar(255) DEFAULT NULL,
  `aoe5_code` varchar(10) DEFAULT NULL,
  `aoe5_label` varchar(90) DEFAULT NULL,
  `aoe5_list` varchar(30) DEFAULT NULL,
  `aoe5_text` varchar(255) DEFAULT NULL,
  `aoe6_code` varchar(10) DEFAULT NULL,
  `aoe6_label` varchar(90) DEFAULT NULL,
  `aoe6_list` varchar(30) DEFAULT NULL,
  `aoe6_text` varchar(255) DEFAULT NULL,
  `aoe7_code` varchar(10) DEFAULT NULL,
  `aoe7_label` varchar(90) DEFAULT NULL,
  `aoe7_list` varchar(30) DEFAULT NULL,
  `aoe7_text` varchar(255) DEFAULT NULL,
  `aoe8_code` varchar(10) DEFAULT NULL,
  `aoe8_label` varchar(90) DEFAULT NULL,
  `aoe8_list` varchar(30) DEFAULT NULL,
  `aoe8_text` varchar(255) DEFAULT NULL,
  `aoe9_code` varchar(10) DEFAULT NULL,
  `aoe9_label` varchar(90) DEFAULT NULL,
  `aoe9_list` varchar(30) DEFAULT NULL,
  `aoe9_text` varchar(255) DEFAULT NULL,
  `aoe10_code` varchar(10) DEFAULT NULL,
  `aoe10_label` varchar(90) DEFAULT NULL,
  `aoe10_list` varchar(30) DEFAULT NULL,
  `aoe10_text` varchar(255) DEFAULT NULL,
  `aoe11_code` varchar(10) DEFAULT NULL,
  `aoe11_label` varchar(90) DEFAULT NULL,
  `aoe11_list` varchar(30) DEFAULT NULL,
  `aoe11_text` varchar(255) DEFAULT NULL,
  `aoe12_code` varchar(10) DEFAULT NULL,
  `aoe12_label` varchar(90) DEFAULT NULL,
  `aoe12_list` varchar(30) DEFAULT NULL,
  `aoe12_text` varchar(255) DEFAULT NULL,
  `aoe13_code` varchar(10) DEFAULT NULL,
  `aoe13_label` varchar(90) DEFAULT NULL,
  `aoe13_list` varchar(30) DEFAULT NULL,
  `aoe13_text` varchar(255) DEFAULT NULL,
  `aoe14_code` varchar(10) DEFAULT NULL,
  `aoe14_label` varchar(90) DEFAULT NULL,
  `aoe14_list` varchar(30) DEFAULT NULL,
  `aoe14_text` varchar(255) DEFAULT NULL,
  `aoe15_code` varchar(10) DEFAULT NULL,
  `aoe15_label` varchar(90) DEFAULT NULL,
  `aoe15_list` varchar(30) DEFAULT NULL,
  `aoe15_text` varchar(255) DEFAULT NULL,
  `aoe16_code` varchar(10) DEFAULT NULL,
  `aoe16_label` varchar(90) DEFAULT NULL,
  `aoe16_list` varchar(30) DEFAULT NULL,
  `aoe16_text` varchar(255) DEFAULT NULL,
  `aoe17_code` varchar(10) DEFAULT NULL,
  `aoe17_label` varchar(90) DEFAULT NULL,
  `aoe17_list` varchar(30) DEFAULT NULL,
  `aoe17_text` varchar(255) DEFAULT NULL,
  `aoe18_code` varchar(10) DEFAULT NULL,
  `aoe18_label` varchar(90) DEFAULT NULL,
  `aoe18_list` varchar(30) DEFAULT NULL,
  `aoe18_text` varchar(255) DEFAULT NULL,
  `aoe19_code` varchar(10) DEFAULT NULL,
  `aoe19_label` varchar(90) DEFAULT NULL,
  `aoe19_list` varchar(30) DEFAULT NULL,
  `aoe19_text` varchar(255) DEFAULT NULL,
  `aoe20_code` varchar(10) DEFAULT NULL,
  `aoe20_label` varchar(90) DEFAULT NULL,
  `aoe20_list` varchar(30) DEFAULT NULL,
  `aoe20_text` varchar(255) DEFAULT NULL,
  `aoe21_code` varchar(10) DEFAULT NULL,
  `aoe21_label` varchar(90) DEFAULT NULL,
  `aoe21_list` varchar(30) DEFAULT NULL,
  `aoe21_text` varchar(255) DEFAULT NULL,
  `aoe22_code` varchar(10) DEFAULT NULL,
  `aoe22_label` varchar(90) DEFAULT NULL,
  `aoe22_list` varchar(30) DEFAULT NULL,
  `aoe22_text` varchar(255) DEFAULT NULL,
  `aoe23_code` varchar(10) DEFAULT NULL,
  `aoe23_label` varchar(90) DEFAULT NULL,
  `aoe23_list` varchar(30) DEFAULT NULL,
  `aoe23_text` varchar(255) DEFAULT NULL,
  `aoe24_code` varchar(10) DEFAULT NULL,
  `aoe24_label` varchar(90) DEFAULT NULL,
  `aoe24_list` varchar(30) DEFAULT NULL,
  `aoe24_text` varchar(255) DEFAULT NULL,
  `aoe25_code` varchar(10) DEFAULT NULL,
  `aoe25_label` varchar(90) DEFAULT NULL,
  `aoe25_list` varchar(30) DEFAULT NULL,
  `aoe25_text` varchar(255) DEFAULT NULL,
  `aoe26_code` varchar(10) DEFAULT NULL,
  `aoe26_label` varchar(90) DEFAULT NULL,
  `aoe26_list` varchar(30) DEFAULT NULL,
  `aoe26_text` varchar(255) DEFAULT NULL,
  `aoe27_code` varchar(10) DEFAULT NULL,
  `aoe27_label` varchar(90) DEFAULT NULL,
  `aoe27_list` varchar(30) DEFAULT NULL,
  `aoe27_text` varchar(255) DEFAULT NULL,
  `aoe28_code` varchar(10) DEFAULT NULL,
  `aoe28_label` varchar(90) DEFAULT NULL,
  `aoe28_list` varchar(30) DEFAULT NULL,
  `aoe28_text` varchar(255) DEFAULT NULL,
  `aoe29_code` varchar(10) DEFAULT NULL,
  `aoe29_label` varchar(90) DEFAULT NULL,
  `aoe29_list` varchar(30) DEFAULT NULL,
  `aoe29_text` varchar(255) DEFAULT NULL,
  `aoe30_code` varchar(10) DEFAULT NULL,
  `aoe30_label` varchar(90) DEFAULT NULL,
  `aoe30_list` varchar(30) DEFAULT NULL,
  `aoe30_text` varchar(255) DEFAULT NULL,
  `aoe31_code` varchar(10) DEFAULT NULL,
  `aoe31_label` varchar(90) DEFAULT NULL,
  `aoe31_list` varchar(30) DEFAULT NULL,
  `aoe31_text` varchar(255) DEFAULT NULL,
  `aoe32_code` varchar(10) DEFAULT NULL,
  `aoe32_label` varchar(90) DEFAULT NULL,
  `aoe32_list` varchar(30) DEFAULT NULL,
  `aoe32_text` varchar(255) DEFAULT NULL,
  `aoe33_code` varchar(10) DEFAULT NULL,
  `aoe33_label` varchar(90) DEFAULT NULL,
  `aoe33_list` varchar(30) DEFAULT NULL,
  `aoe33_text` varchar(255) DEFAULT NULL,
  `aoe34_code` varchar(10) DEFAULT NULL,
  `aoe34_label` varchar(90) DEFAULT NULL,
  `aoe34_list` varchar(30) DEFAULT NULL,
  `aoe34_text` varchar(255) DEFAULT NULL,
  `aoe35_code` varchar(10) DEFAULT NULL,
  `aoe35_label` varchar(90) DEFAULT NULL,
  `aoe35_list` varchar(30) DEFAULT NULL,
  `aoe35_text` varchar(255) DEFAULT NULL,
  `aoe36_code` varchar(10) DEFAULT NULL,
  `aoe36_label` varchar(90) DEFAULT NULL,
  `aoe36_list` varchar(30) DEFAULT NULL,
  `aoe36_text` varchar(255) DEFAULT NULL,
  `aoe37_code` varchar(10) DEFAULT NULL,
  `aoe37_label` varchar(90) DEFAULT NULL,
  `aoe37_list` varchar(30) DEFAULT NULL,
  `aoe37_text` varchar(255) DEFAULT NULL,
  `aoe38_code` varchar(10) DEFAULT NULL,
  `aoe38_label` varchar(90) DEFAULT NULL,
  `aoe38_list` varchar(30) DEFAULT NULL,
  `aoe38_text` varchar(255) DEFAULT NULL,
  `aoe39_code` varchar(10) DEFAULT NULL,
  `aoe39_label` varchar(90) DEFAULT NULL,
  `aoe39_list` varchar(30) DEFAULT NULL,
  `aoe39_text` varchar(255) DEFAULT NULL,
  `aoe40_code` varchar(10) DEFAULT NULL,
  `aoe40_label` varchar(90) DEFAULT NULL,
  `aoe40_list` varchar(30) DEFAULT NULL,
  `aoe40_text` varchar(255) DEFAULT NULL,
  `aoe41_code` varchar(10) DEFAULT NULL,
  `aoe41_label` varchar(90) DEFAULT NULL,
  `aoe41_list` varchar(30) DEFAULT NULL,
  `aoe41_text` varchar(255) DEFAULT NULL,
  `aoe42_code` varchar(10) DEFAULT NULL,
  `aoe42_label` varchar(90) DEFAULT NULL,
  `aoe42_list` varchar(30) DEFAULT NULL,
  `aoe42_text` varchar(255) DEFAULT NULL,
  `aoe43_code` varchar(10) DEFAULT NULL,
  `aoe43_label` varchar(90) DEFAULT NULL,
  `aoe43_list` varchar(30) DEFAULT NULL,
  `aoe43_text` varchar(255) DEFAULT NULL,
  `aoe44_code` varchar(10) DEFAULT NULL,
  `aoe44_label` varchar(90) DEFAULT NULL,
  `aoe44_list` varchar(30) DEFAULT NULL,
  `aoe44_text` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `parent_idx` (`parent_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `form_labcorp_order_item`
--

CREATE TABLE IF NOT EXISTS `form_labcorp_order_item` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `parent_id` bigint(20) NOT NULL,
  `date` datetime NOT NULL,
  `pid` bigint(20) NOT NULL,
  `user` varchar(255) NOT NULL,
  `groupname` varchar(255) DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT NULL,
  `activity` tinyint(4) DEFAULT NULL,
  `status` varchar(16) DEFAULT 'i',
  `priority` varchar(16) DEFAULT 'n',
  `test_code` varchar(255) DEFAULT NULL,
  `test_text` varchar(255) DEFAULT NULL,
  `test_profile` tinyint(4) DEFAULT NULL,
  `test_zseg` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `parent_idx` (`parent_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Remove labcorp data from table `list_options`
--

DELETE FROM `list_options` WHERE `list_id` LIKE 'LabCorp%' OR `option_id` LIKE 'LabCorp%' ;

--
-- Insert labcorp data into table `list_options`
--

INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`, `mapping`, `notes`) VALUES
('LabCorp_Accounts', '90990605', 'General', 1, 1, 0, '', ''),
('LabCorp_Age_Days', '0', '0', 1, 0, 0, '', ''),
('LabCorp_Age_Days', '1', '1', 2, 0, 0, '', ''),
('LabCorp_Age_Days', '2', '2', 3, 0, 0, '', ''),
('LabCorp_Age_Days', '3', '3', 4, 0, 0, '', ''),
('LabCorp_Age_Days', '4', '4', 5, 0, 0, '', ''),
('LabCorp_Age_Days', '5', '5', 6, 0, 0, '', ''),
('LabCorp_Age_Days', '6', '6', 7, 0, 0, '', ''),
('LabCorp_Billing', 'C', 'Client', 3, 0, 0, '', ''),
('LabCorp_Billing', 'L1', 'Indigent', 4, 0, 0, '', ''),
('LabCorp_Billing', 'P', 'Patient', 2, 0, 0, '', ''),
('LabCorp_Billing', 'T', 'Third Party', 1, 1, 0, '', ''),
('LabCorp_Blood_Hispanic', '1', 'Yes', 10, 0, 0, '', ''),
('LabCorp_Blood_Hispanic', '2', 'No', 20, 0, 0, '', ''),
('LabCorp_Blood_Hispanic', '3', 'Unknown', 30, 0, 0, '', ''),
('LabCorp_Blood_Purpose', 'F', 'Follow Up', 30, 0, 0, '', ''),
('LabCorp_Blood_Purpose', 'I', 'Initial', 10, 0, 0, '', ''),
('LabCorp_Blood_Purpose', 'R', 'Repeat', 20, 0, 0, '', ''),
('LabCorp_Blood_Race', '1', 'White', 10, 0, 0, '', ''),
('LabCorp_Blood_Race', '2', 'Black', 20, 0, 0, '', ''),
('LabCorp_Blood_Race', '3', 'American Indian', 30, 0, 0, '', ''),
('LabCorp_Blood_Race', '4', 'Asian', 40, 0, 0, '', ''),
('LabCorp_Blood_Race', '5', 'Other', 50, 0, 0, '', ''),
('LabCorp_Blood_Race', '9', 'Unknown', 99, 0, 0, '', ''),
('LabCorp_Blood_Type', 'F', 'Fingerstick', 20, 0, 0, '', ''),
('LabCorp_Blood_Type', 'V', 'Venous', 10, 0, 0, '', ''),
('LabCorp_Body_Site', 'ZCY1', 'Cervical', 1, 0, 0, '', ''),
('LabCorp_Body_Site', 'ZCY2', 'Endocervical', 2, 0, 0, '', ''),
('LabCorp_Body_Site', 'ZCY3', 'Labia-Vulva', 3, 0, 0, '', ''),
('LabCorp_Body_Site', 'ZCY37', 'Labium Majus', 6, 0, 0, '', ''),
('LabCorp_Body_Site', 'ZCY38', 'Labium Minus', 7, 0, 0, '', ''),
('LabCorp_Body_Site', 'ZCY39', 'Vulva', 8, 0, 0, '', ''),
('LabCorp_Body_Site', 'ZCY4', 'Vaginal', 4, 0, 0, '', ''),
('LabCorp_Body_Site', 'ZCY5', 'Endometrial', 5, 0, 0, '', ''),
('LabCorp_Collection', 'ZCY10', 'Broom-Alone', 5, 0, 0, '', ''),
('LabCorp_Collection', 'ZCY11', 'Other Technique', 6, 0, 0, '', ''),
('LabCorp_Collection', 'ZCY6', 'Swab-Spatula', 1, 0, 0, '', ''),
('LabCorp_Collection', 'ZCY7', 'Brush-Spatula', 2, 0, 0, '', ''),
('LabCorp_Collection', 'ZCY8', 'Spatula-Alone', 3, 0, 0, '', ''),
('LabCorp_Collection', 'ZCY9', 'Brush-Alone', 4, 0, 0, '', ''),
('LabCorp_Cytology', 'ZCY30', 'Negative', 1, 0, 0, '', ''),
('LabCorp_Cytology', 'ZCY31', 'Atypical', 2, 0, 0, '', ''),
('LabCorp_Cytology', 'ZCY32', 'Dysplasia', 3, 0, 0, '', ''),
('LabCorp_Cytology', 'ZCY33', 'Ca-In-Situ', 4, 0, 0, '', ''),
('LabCorp_Cytology', 'ZCY34', 'Invasive', 5, 0, 0, '', ''),
('LabCorp_Cytology', 'ZCY35', 'Other', 8, 0, 0, '', ''),
('LabCorp_Cytology', 'ZCY42', 'Dysplasia Low', 6, 0, 0, '', ''),
('LabCorp_Cytology', 'ZCY43', 'Dysplasia High', 7, 0, 0, '', ''),
('LabCorp_Ethnicity', 'hisp_or_latin', 'H', 1, 0, 0, '', 'ID is OpenEMR code'),
('LabCorp_Ethnicity', 'not_hisp_or_latino', 'N', 2, 0, 0, '', 'TITLE is LabCorp code'),
('LabCorp_Ethnicity', 'unknown', 'U', 3, 1, 0, '', ''),
('LabCorp_Fetuses', '1', '1', 2, 0, 0, '', ''),
('LabCorp_Fetuses', '2', '2', 3, 0, 0, '', ''),
('LabCorp_Fetuses', '3', '3', 4, 0, 0, '', ''),
('LabCorp_Fetuses', '4', '4', 5, 0, 0, '', ''),
('LabCorp_Fetuses', '5', '5', 6, 0, 0, '', ''),
('LabCorp_Fetuses', '6', '6', 7, 0, 0, '', ''),
('LabCorp_Fetuses', '7', '7', 8, 0, 0, '', ''),
('LabCorp_Fetuses', '8', '8', 9, 0, 0, '', ''),
('LabCorp_Fetuses', '9', '9', 10, 0, 0, '', ''),
('LabCorp_Fetuses', '_blank', '', 1, 1, 0, '', ''),
('LabCorp_GA_Calc', 'ZSA3.1', 'LMP (date required)', 1, 0, 0, '', ''),
('LabCorp_GA_Calc', 'ZSA4.1', 'Ultrasound Method', 3, 0, 0, '', ''),
('LabCorp_GA_Calc', 'ZSA5.1', 'EDD/EDC (date required)', 2, 0, 0, '', ''),
('LabCorp_Handling', 'follow', 'Follow-Up Required', 3, 0, 0, '', ''),
('LabCorp_Handling', 'note', 'Notify Physician', 1, 0, 0, '', ''),
('LabCorp_Handling', 'pat', 'Notify Patient', 2, 0, 0, '', ''),
('LabCorp_Insurance', '[ins id]', '[labcorp id]', 0, 0, 0, '', ''),
('LabCorp_Options', 'A', 'Asian', 1, 0, 0, '', ''),
('LabCorp_Options', 'B', 'Black/African American', 2, 0, 0, '', ''),
('LabCorp_Options', 'C', 'White/Caucasian', 3, 0, 0, '', ''),
('LabCorp_Options', 'H', 'Hispanic', 4, 0, 0, '', ''),
('LabCorp_Options', 'I', 'American Indian', 5, 0, 0, '', ''),
('LabCorp_Options', 'O', 'Other Race', 6, 0, 0, '', ''),
('LabCorp_Options', 'X', 'Not Indicated', 9, 0, 0, '', ''),
('LabCorp_Patient', 'ZCY21', 'Pregnant', 1, 0, 0, '', ''),
('LabCorp_Patient', 'ZCY22', 'Lactating', 2, 0, 0, '', ''),
('LabCorp_Patient', 'ZCY23', 'Oral Contraceptives', 3, 0, 0, '', ''),
('LabCorp_Patient', 'ZCY24', 'Menopausal', 4, 0, 0, '', ''),
('LabCorp_Patient', 'ZCY25', 'Estro-Rx', 5, 0, 0, '', ''),
('LabCorp_Patient', 'ZCY26', 'PMP-Bleeding', 6, 0, 0, '', ''),
('LabCorp_Patient', 'ZCY27', 'Post-Part', 7, 0, 0, '', ''),
('LabCorp_Patient', 'ZCY28', 'IUD', 8, 0, 0, '', ''),
('LabCorp_Patient', 'ZCY29', 'All-Other-Pat', 9, 0, 0, '', ''),
('LabCorp_Previous', 'ZCY13', 'None', 1, 0, 0, '', ''),
('LabCorp_Previous', 'ZCY14', 'Hyst', 2, 0, 0, '', ''),
('LabCorp_Previous', 'ZCY15', 'Coniza', 3, 0, 0, '', ''),
('LabCorp_Previous', 'ZCY16', 'Colp-BX', 4, 0, 0, '', ''),
('LabCorp_Previous', 'ZCY17', 'Laser-Vap', 5, 0, 0, '', ''),
('LabCorp_Previous', 'ZCY18', 'Cyro', 6, 0, 0, '', ''),
('LabCorp_Previous', 'ZCY19', 'Radiation', 7, 0, 0, '', ''),
('LabCorp_Previous', 'ZCY40', 'Hysterectomy, Total', 8, 0, 0, '', ''),
('LabCorp_Previous', 'ZCY41', 'Hysterectomy, Partial', 9, 0, 0, '', ''),
('LabCorp_Race', 'amer_ind_or_alaska_native', 'I', 1, 0, 0, '', 'ID is OpenEMR code'),
('LabCorp_Race', 'asian', 'A', 2, 0, 0, '', 'TITLE is LabCorp code'),
('LabCorp_Race', 'black_or_afri_amer', 'B', 3, 0, 0, '', ''),
('LabCorp_Race', 'native_hawai_or_pac_island', 'C', 4, 0, 0, '', ''),
('LabCorp_Race', 'unknown', 'X', 6, 1, 0, '', 'Not Indicated'),
('LabCorp_Race', 'white', 'C', 5, 0, 0, '', ''),
('LabCorp_Site_Identifiers', '3', 'TE028126', 0, 1, 0, '', ''),
('LabCorp_WC_Insurance', 'atena', 'Atena Workmans Comp', 0, 0, 0, '', ''),
('LabCorp_Yes_No', 'N', 'No', 2, 0, 0, '', ''),
('LabCorp_Yes_No', 'Y', 'Yes', 3, 0, 0, '', '');
